version: "3.5"
services:
  mongo-test:
    container_name: dx-mongo-test
    restart: always
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - 27019:27017
    volumes:
      - dx_mongo_data_test:/data/db
    env_file:
      - .env

  server-test:
    container_name: dx-server-test
    restart: always
    build: ./dx.server
    image: dx-server-test
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_AUTH_SOURCE=${MONGO_AUTH_SOURCE}
      - BACKEND_SUBDOMAIN=${BACKEND_SUBDOMAIN}
      - MAIN_DOMAIN=${MAIN_DOMAIN}
      - DX_BACKEND_DIR=${DX_BACKEND_DIR}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - ENV_TYPE=${ENV_TYPE}
    ports:
      - 4202:4200
    depends_on:
      - mongo-test
    env_file:
      - .env
    volumes:
      - ./dx.backend/:/app/dx.backend/
      - ./dx.server/logging/:/app/logging/

  backend-test:
    container_name: dx-backend-test
    restart: always
    build:
      context: ./dx.backend
    image: dx-backend-test
    environment:
      - DATA_EXPLORER_SSR=${DATA_EXPLORER_SSR}
    ports:
      - 4006:4004
    depends_on:
      - server-test
    env_file:
      - .env
    volumes:
      - ./dx.backend/staging/:/app/staging/
      - ./dx.backend/logging/:/app/logging/
      - ./dx.backend/parsed-data-files/:/app/parsed-data-files/
      - ./dx.backend/sample-data-files/:/app/sample-data-files/
    deploy:
      resources:
        limits:
          memory: 8G

  ai-api-test:
    container_name: dx-ai-api-test
    build:
      context: ./general-ai-api
    image: dx-ai-api-test
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      # path to be changed in deployment, this path assumes as part of DX central repo
      - ./dx.backend/parsed-data-files:/parsed-data-files
    env_file:
      - .env
    ports:
      - 5002:5000

  frontend-test:
    container_name: dx-frontend-test
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        - REACT_APP_API=${REACT_APP_API}
        - REACT_APP_GOOGLE_API_CLIENT_ID=${REACT_APP_GOOGLE_API_CLIENT_ID}
        - REACT_APP_GOOGLE_API_DEV_KEY=${REACT_APP_GOOGLE_API_DEV_KEY}
        - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
        - REACT_APP_AUTH0_CLIENT=${REACT_APP_AUTH0_CLIENT}
        - REACT_APP_AUTH0_AUDIENCE=${REACT_APP_AUTH0_AUDIENCE}
        - REACT_APP_HUBSPOT_PORTAL_ID=${REACT_APP_HUBSPOT_PORTAL_ID}
        - REACT_APP_HUBSPOT_SUBSCRIBE_FORM_ID=${REACT_APP_HUBSPOT_SUBSCRIBE_FORM_ID}
    image: dx-client-test
    ports:
      - 82:80
    depends_on:
      - server-test
      - backend-test
    environment:
      - REACT_APP_API=${REACT_APP_API}
      - REACT_APP_CMS_TOKEN=${REACT_APP_CMS_TOKEN}
      - REACT_APP_MAPBOX_TOKEN=${REACT_APP_MAPBOX_TOKEN}
      - REACT_APP_CMS_API=${REACT_APP_CMS_API}
      - REACT_APP_GOOGLE_API_CLIENT_ID=${REACT_APP_GOOGLE_API_CLIENT_ID}
      - REACT_APP_GOOGLE_API_DEV_KEY=${REACT_APP_GOOGLE_API_DEV_KEY}
      - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
      - REACT_APP_AUTH0_CLIENT=${REACT_APP_AUTH0_CLIENT}
      - REACT_APP_AUTH0_AUDIENCE=${REACT_APP_AUTH0_AUDIENCE}
      - REACT_APP_HUBSPOT_PORTAL_ID=${REACT_APP_HUBSPOT_PORTAL_ID}
      - REACT_APP_HUBSPOT_SUBSCRIBE_FORM_ID=${REACT_APP_HUBSPOT_SUBSCRIBE_FORM_ID}
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 8G
    volumes:
      - ./dx.client/test/:/app/client/test/

volumes:
  dx_mongo_data_test:
