FROM node:22.21-alpine3.21

# For development add /bin/bash
RUN apk update && apk add bash

# Install and link the charts
WORKDIR /app/charts/
COPY ./rawgraphs-charts ./
RUN yarn install --network-timeout 100000
RUN yarn build
RUN yarn link

# Set up the client
WORKDIR /app/client

# Copy the package.json and yarn.lock files
COPY ./dx.client ./

# Install the project dependencies and link the charts
RUN yarn link "@rawgraphs/rawgraphs-charts" && yarn install --network-timeout 100000

# Start the development server
CMD ["yarn", "docker"]
